A-Level - Python 4
Grimnebylen/OOP_Practis pull request #1
Opened 2022-12-09 14:11 UTC by Grimnebylen

Мазур Сергій

2022-12-12 11:20 UTC, shorodilov requested changes
Потребує виправлень

2022-12-14 21:46 UTC, Grimnebylen commented on opp.py
> +        if item not in self.products:
Виправлено.

2022-12-14 21:46 UTC, Grimnebylen commented on opp.py
> +            price += product[1] * self.products_quantity[self.products.index(product)]
Виправлено.

2022-12-15 09:33 UTC, shorodilov approved these changes
LGTM

2022-12-20 18:18 UTC, Grimnebylen commented
Success

2022-12-20 18:19 UTC, merged